import os
import argparse
import torch
import time
import datetime
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    TrainerCallback
)
from peft import LoraConfig, get_peft_model
from trl import SFTTrainer

class CustomLoggingCallback(TrainerCallback):
    def __init__(self):
        super().__init__()
        self.start_time = None
        
    def on_train_begin(self, args, state, control, **kwargs):
        self.start_time = time.time()
        print("\nStarting Training Phase...")
        
    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs is None:
            return
            
        step = state.global_step
        max_steps = state.max_steps
        
        # GPU Memory usage
        if torch.cuda.is_available():
            mem_allocated = torch.cuda.memory_allocated() / (1024**3)
            mem_reserved = torch.cuda.memory_reserved() / (1024**3)
            mem_str = f"GPU Mem: {mem_allocated:.2f}GB alloc / {mem_reserved:.2f}GB res"
        else:
            mem_str = "CPU Mode"
            
        # Loss
        loss = logs.get('loss', 'N/A')
        
        # ETA calculation
        if step > 0 and self.start_time is not None:
            elapsed = time.time() - self.start_time
            steps_per_sec = step / elapsed
            rem_steps = max_steps - step
            rem_time = rem_steps / steps_per_sec
            eta_str = str(datetime.timedelta(seconds=int(rem_time)))
        else:
            eta_str = "Calculating..."
            
        print(f"[Step {step}/{max_steps}] Loss: {loss} | {mem_str} | ETA: {eta_str}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--use_sample", action="store_true", help="Use the fast sample dataset generated by dataset_utils")
    args = parser.parse_args()

    print("Starting Cooking AI SLM Fine-Tuning Process...")
    
    # TF32 Optimization for Ampere/RTX 40-series cards
    if torch.cuda.is_available():
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
        print(f"CUDA GPU detected: {torch.cuda.get_device_name(0)}")
        device_map_config = "cuda"
    else:
        print("WARNING: CUDA GPU not found. Falling back to CPU automatically.")
        device_map_config = "cpu"
    
    # Paths
    dataset_path = "data/cooking_finetune_sample.json" if args.use_sample else "data/cooking_finetune.json"
    model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
    output_dir = "models/cooking-slm-sample/" if args.use_sample else "models/cooking-slm/"
    
    if not os.path.exists(dataset_path):
        print(f"ERROR: Dataset not found at {dataset_path}.")
        if args.use_sample:
            print("Please run 'python src/dataset_utils.py --sample' first to generate it.")
        else:
            print("Please ensure the primary dataset exists.")
        return
        
    print(f"Loading dataset from {dataset_path}...")
    dataset = load_dataset("json", data_files=dataset_path, split="train")
    
    print(f"Loading base model {model_id}...")
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"
    
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        device_map=device_map_config
    )
    
    print("Applying LoRA configuration...")
    peft_config = LoraConfig(
        r=16,
        lora_alpha=32,
        lora_dropout=0.05,
        target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
        task_type="CAUSAL_LM"
    )
    
    model = get_peft_model(model, peft_config)
    model.print_trainable_parameters()
    
    # Crucial: Cast trainable params back to fp32 directly bypassing 'fp16 unscale' crashes
    for param in model.parameters():
        if param.requires_grad:
            param.data = param.data.to(torch.float32)
    
    print("Setting up safe and exact training arguments for 6GB VRAM...")
    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=2,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        learning_rate=2e-4,
        fp16=True, 
        logging_steps=50,
        save_steps=500,
        warmup_steps=100,
        optim="adamw_torch",
        save_total_limit=2,
        disable_tqdm=True # Relying on CustomLogger
    )
    
    print("Initializing SFTTrainer...")
    trainer = SFTTrainer(
        model=model,
        train_dataset=dataset,
        peft_config=peft_config,
        formatting_func=lambda x: x["text"],
        max_seq_length=512, 
        tokenizer=tokenizer,
        args=training_args,
        packing=False
    )
    
    trainer.add_callback(CustomLoggingCallback())
    
    print("Starting exact end-to-end training. Profiling GPU memory efficiency and ETA...")
    trainer.train()
    
    print(f"\nTraining completed! Saving optimized model to {output_dir}...")
    trainer.model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print("Model effectively saved and ready for inference!")

if __name__ == "__main__":
    main()
